INSERT INTO equipment_categories (id, name) VALUES(1, 'Terrraplanagem');
INSERT INTO equipment_categories (id, name) VALUES(2, 'Bancada');
INSERT INTO equipment_categories (id, name) VALUES(3, 'Manuais');
INSERT INTO equipment_categories (id, name) VALUES(4, 'Pavimentação');
INSERT INTO equipment_categories (id, name) VALUES(5, 'Concretagem');
INSERT INTO equipment_categories (id, name) VALUES(6, 'Trabalho em altura');
INSERT INTO equipment_categories (id, name) VALUES(7, 'Motor a combustão');
INSERT INTO equipment_categories (id, name) VALUES(8, 'Trabalho a quente');
INSERT INTO equipment_categories (id, name) VALUES(9, 'Elevação de carga');

INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Escavadeira');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Carregadeira');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Retroescavadeira');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Motoniveladora');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Rolo compactador liso');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Bobcat');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Mini Dumper');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Caminhão basculante');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Caminhão pipa');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Sapo compactador');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (1,'Rolo compactador pé de carneiro');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (2,'Serra para madeira de bancada');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (2,'Policorte');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (2,'Esmeril');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (3,'Serra manual de piso e mármore');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (3,'Serra manual de madeira');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (3,'Serra manual de meia esquadria');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (3,'Pistola finca pino');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (3,'Furadeira de impacto');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (3,'Martelete rompedor elétrico');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (3,'Vibrador elétrico');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (4,'Caminhão caldeira de asfalto');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (4,'Pavimentadora de asfalto');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (4,'Aplicador termoplástico por extrusão');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (5,'Caminhão betoneira');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (5,'Caminhão bomba de concreto');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (5,'Bomba de concreto projetado');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (5,'Bomba de argamassa projetada');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (5,'Vibrador elétrico');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (5,'Régua vibratória');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (5,'Betoneira estacionária');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (6,'Plataforma cremalheira');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (6,'Cadeirinha suspensa');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (6,'Andaime Manual suspenso');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (6,'Andaime elétrico suspenso');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (6,'Andaime de cavalete');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (6,'Andaime fachadeiro');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (6,'Andaime fixo');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (6,'Andaime móvel');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (7,'Martelete pneumático');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (7,'Compressor');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (7,'Gerador a combustão');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (7,'Vibrador a gasolina');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (7,'Régua vibratória');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (7,'Acabadora alisadora de concreto');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (8,'Solda elétrica');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (8,'Solda oxiacetileno');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (8,'Maçarico de GLP');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (9,'Empilhadeira');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (9,'Caminhão munck');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (9,'Guindaste');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (9,'Plataforma móvel');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (9,'Guincho rápido "velox"');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (9,'Grua');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (9,'Mini grua');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (9,'Elevador a cabo');
INSERT INTO equipment_types (equipment_category_id, name) VALUES (9,'Elevador cremalheira');


