INSERT INTO qualities (name) VALUES ('NR 5 - CIPA - formação de cipeiros (20 horas)');
INSERT INTO qualities (name) VALUES ('Registro profissional de medicina');
INSERT INTO qualities (name) VALUES ('Registro profissional de engenharia de segurança');
INSERT INTO qualities (name) VALUES ('NR 10 - Básico (40 horas)');
INSERT INTO qualities (name) VALUES ('NR 10 - Básico - reciclagem (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 10 - SEP (Sistema Elétrico de Potência)');
INSERT INTO qualities (name) VALUES ('NR 10 - SEP (Sistema Elétrico de Potência) reciclagem');
INSERT INTO qualities (name) VALUES ('NR 11 - Operador de elevador (16 horas)');
INSERT INTO qualities (name) VALUES ('NR 11 - Operador de elevador - recicagem (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 11 - Operador de guindaste / grua (40 horas - 16 horas)');
INSERT INTO qualities (name) VALUES ('NR 11 - Operador de guindaste / grua - reciclagem (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 11 - Operador de empilhadeira (16 horas)');
INSERT INTO qualities (name) VALUES ('NR 11 - Operador de empilhadeira - reciclagem (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 11 - Operador de ponte rolante');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Geral (16 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Geral - reciclagem (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Moto Serra (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Operador de Policorte (x horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Betoneira (16 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Betoneira - reciclagem (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Maçarico (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Máquina de solda (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Martelete (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Policorte (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Roçadeira (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 12 - Segurança no trabalho em máquinas e equipamentos - Esmeril (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 13 - Caldeiras e vasos de pressão (40 horas)');
INSERT INTO qualities (name) VALUES ('NR 18 - Admissional (6 horas)');
INSERT INTO qualities (name) VALUES ('NR 18 - Periódico');
INSERT INTO qualities (name) VALUES ('NR 18 - PTA - Plataforma de trabalho Aéreo (16 horas)');
INSERT INTO qualities (name) VALUES ('NR 18 - PTA - Plataforma de trabalho Aéreo - reciclagem (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 18 - Curso Sinaleiro e Amarrador de Cargas (16 horas)');
INSERT INTO qualities (name) VALUES ('NR 18 - Curso Sinaleiro e Amarrador de Cargas - reciclagem (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 18 - Curso Balancim e Andaime (16 horas)');
INSERT INTO qualities (name) VALUES ('NR 18 - Curso Balancim e Andaime - reciclagem (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 18 - Segurança no trabalho em máquinas e equipamentos - Serra Circular (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 20 - Segurança e Saúde no Trabalho com Inflamáveis e Combustíveis - Intermediário (16 horas)');
INSERT INTO qualities (name) VALUES ('NR 20 - Segurança e Saúde no Trabalho com Inflamáveis e Combustíveis - Integração (4 horas)');
INSERT INTO qualities (name) VALUES ('NR 33 - Segurança e Saúde no trabalho em espaços confinados - trabalhadores autorizados e vigias (16 horas)');
INSERT INTO qualities (name) VALUES ('NR 33 - Segurança e Saúde no trabalho em espaços confinados - supervisor de espaços confinados (40 horas)');
INSERT INTO qualities (name) VALUES ('NR 35 - Trabalho em altura - inicial (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 35 - Trabalho em altura - periódico (8 horas)');
INSERT INTO qualities (name) VALUES ('NR 35 - Supervisor de trabalho em altura (40 horas)');
INSERT INTO qualities (name) VALUES ('NR 23 - Combate a incêndio');
INSERT INTO qualities (name) VALUES ('Primeiros Socorros');

