spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafety_db?nullNamePatternMatchesAll=true
    username: ssafety_usr
    password: secret

liquibase:
  change-log: classpath:liquibase/changelog.xml
  url: jdbc:mysql://localhost:3306/ssafety_db?nullNamePatternMatchesAll=true
  user: ssafety_usr
  password: secret
  drop-first: false