import { NgModule } from '@angular/core';
import {
    MdChipsModule,
    MdCheckboxModule,
    MdSidenavModule,
    MdButtonModule,
    MdIconModule,
    MdMenuModule,
    MdListModule,
    MdInputModule,
    MdSelectModule,
    MdTooltipModule,
    MdToolbarModule,
    MdCardModule,
    MdTabsModule,
    MdRadioModule,
    MdSnackBarModule,
    MdGridListModule,
    MdDialogModule,
} from '@angular/material';

@NgModule({
    imports: [
        MdChipsModule,
        MdButtonModule,
        MdMenuModule,
        MdCheckboxModule,
        MdSidenavModule,
        MdButtonModule,
        MdIconModule,
        MdListModule,
        MdInputModule,
        MdSelectModule,
        MdTooltipModule,
        MdToolbarModule,
        MdCardModule,
        MdTabsModule,
        MdRadioModule,
        MdSnackBarModule,
        MdGridListModule,
        MdDialogModule
    ],
    exports: [
        MdChipsModule,
        MdButtonModule,
        MdMenuModule,
        MdCheckboxModule,
        MdSidenavModule,
        MdButtonModule,
        MdIconModule,
        MdListModule,
        MdInputModule,
        MdSelectModule,
        MdTooltipModule,
        MdToolbarModule,
        MdCardModule,
        MdTabsModule,
        MdRadioModule,
        MdSnackBarModule,
        MdGridListModule,
        MdDialogModule
    ],
})
export class MaterialModule { }
